#!/usr/bin/perl -w
# This script (sophomorix-test-2) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# Bibliotheken
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 check_options
                                 time_stamp_AD 
                                 get_passwd_charlist
                                 get_plain_password
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_ou_add
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_dns_get
                                 AD_user_create
                                 AD_workstation_create
                                 AD_group_create
                                 AD_group_addmember
                                 AD_user_kill
                                 AD_workstation_kill
                                 AD_object_search
                                 AD_get_name_tokened
                                    );
use Sophomorix::SophomorixTest qw(
                                 AD_object_nonexist
                                 AD_test_object
                                 AD_workstations_any
                                 AD_examaccounts_any
                                 );

$Conf::log_level=1;
my $help=0;

my $copy_wsfile_1=0;
my $copy_wsfile_2=0;
my $copy_wsfile_3=0;
my $copy_wsfile_4=0;
my $copy_wsfile_5=0;
my $test_ws_1=0;
my $test_ws_2=0;
my $test_ws_3=0;
my $test_ws_4=0;
my $test_ws_5=0;



my $ou="";
my $school_token="";
my $room="";
my $computer="";
my $role="";
# calculated

my $login="";
my $plain_password;
my $ws_count=0;
my $birthdate="1970-01-01";

my $testopt=GetOptions(
           "help|h" => \$help,
           "verbose|v+" => \$Conf::log_level,
           "copy-wsfile-1" => \$copy_wsfile_1,
           "test-ws-1" => \$test_ws_1,
           "copy-wsfile-2" => \$copy_wsfile_2,
           "test-ws-2" => \$test_ws_2,
           "copy-wsfile-3" => \$copy_wsfile_3,
           "test-ws-3" => \$test_ws_3,
           "copy-wsfile-4" => \$copy_wsfile_4,
           "test-ws-4" => \$test_ws_4,
           "copy-wsfile-5" => \$copy_wsfile_5,
           "test-ws-5" => \$test_ws_5,
  );


# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);




my ($ldap,$root_dse) = &AD_bind_admin();
my $root_dns=&AD_dns_get($root_dse);


# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-test-2 tests the addition of ExamAccounts and workstation accounts.

Options
  -h  / --help

Step by step Test:
  Copy workstations/classrooms file (Step 1):
      sophomorix-test-2 --copy-wsfile-1
  Import the file:
      sophomorix-workstation
  Run the tests:
      sophomorix-test-2 --test-ws-1

Step 2-4 are missing

  Copy EMPTY workstations/classrooms file (Step 5):
      sophomorix-test-2 --copy-wsfile-5
  Import the file:
      sophomorix-workstation
  Run the tests:
      sophomorix-test-2 --test-ws-5
');
   print "\n";
   exit;
}




############################################################
# Check preliminaries
############################################################
my $host_workstation=$DevelConf::path_conf_host."/workstations";
my $host_classroom=$DevelConf::path_conf_host."/classrooms";
my $testdata="/usr/share/sophomorix-developer/testdata";
my $wsfile_1=$testdata."/workstations-1";
my $wsfile_2=$testdata."/workstations-2";
my $wsfile_3=$testdata."/workstations-3";
my $wsfile_4=$testdata."/workstations-4";
my $wsfile_5=$testdata."/workstations-5";

my $crfile_1=$testdata."/classrooms-1";
my $crfile_2=$testdata."/classrooms-2";
my $crfile_3=$testdata."/classrooms-3";
my $crfile_4=$testdata."/classrooms-4";
my $crfile_5=$testdata."/classrooms-5";



my $time_stamp_AD=&time_stamp_AD();
my @passwort_zeichen=&get_passwd_charlist();
# ou's that have been created in this script
my %ou_created=();
$ou_created{$ou}="created";
my $room_token;
my $login_token;
my $examaccount_token;


############################################################
# Step 1
############################################################

# --copy-wsfile-1
if ($copy_wsfile_1==1){
    # copy workstations-1
    system("cp -v $wsfile_1 $host_workstation");
    system("cp -v $crfile_1 $host_classroom");
}

if ($test_ws_1==1){
    # j1008p01
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008p01,OU=bsz-j1008,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"bsz-j1008p01",
                   sAMAccountname=>"bsz-j1008p01",
                   sn=>"Account",
                   sophomorixAdminClass => "bsz-j1008",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-j1008",
                   not_memberOf => "bsz-students,teachers,bsz-teachers,lin-teachers",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008,OU=Rooms,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-j1008",
                   memberOf => "bsz-examaccounts",
                   not_memberOf => "bsz-teachers",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-examaccounts,OU=Rooms,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-examaccounts",
                   memberOf => "multi-examaccounts",
                   not_memberOf => "teachers,students",
                  });

    # J1008P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-J1008P01,OU=bsz-j1008,OU=Workstations,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Workstation BSZ-J1008P01",
                   name=>"BSZ-J1008P01",
                   cn=>"BSZ-J1008P01",
                   sAMAccountname=>"BSZ-J1008P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "workstation",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-J1008P01.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-J1008P01,".
                                           "HOST/BSZ-J1008P01.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-J1008P01,".
                                           "RestrictedKrbHost/BSZ-J1008P01.".$root_dns.",",
                  });
}


############################################################
# Step 2
############################################################
# --copy-wsfile-2
if ($copy_wsfile_2==1){
    # copy workstations-2
    system("cp -v $wsfile_2 $host_workstation");
    system("cp -v $crfile_2 $host_classroom");
}


if ($test_ws_2==1){


}


############################################################
# Step 3
############################################################
# --copy-wsfile-3
if ($copy_wsfile_3==1){
    # copy workstations-3
    system("cp -v $wsfile_3 $host_workstation");
    system("cp -v $crfile_3 $host_classroom");
}


if ($test_ws_3==1){


}


############################################################
# Step 4
############################################################
# --copy-wsfile-4
if ($copy_wsfile_4==1){
    # copy workstations-4
    system("cp -v $wsfile_4 $host_workstation");
    system("cp -v $crfile_4 $host_classroom");
}

if ($test_ws_4==1){


}


############################################################
# Step 5  empty file
############################################################
# --copy-wsfile-5
if ($copy_wsfile_5==1){
    # copy workstations-5
    system("cp -v $wsfile_5 $host_workstation");
    system("cp -v $crfile_5 $host_classroom");
}


if ($test_ws_5==1){
    &AD_workstations_any($ldap,$root_dse);
    &AD_examaccounts_any($ldap,$root_dse);
}



############################################################
# Delete Accounts
############################################################


############################################################
# Check deletion
############################################################


## --test-kill-ea  
#if ($test_kill_ea==1){
#
#&AD_object_nonexist($ldap,$root_dse,"user","j1010p01");
#&AD_object_nonexist($ldap,$root_dse,"user","j1010p02");
#
#}

&AD_unbind_admin($ldap);



