#!/usr/bin/perl -w
# This script (sophomorix-test) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# Bibliotheken
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 check_options
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_get_base
                                 AD_object_search
                                    );
use Sophomorix::SophomorixTest qw(
                                 AD_test_object_exist
                                 );

$Conf::log_level=1;
my $add=0;
my $move=0;
my $kill=0;
my $help=0;
my $skip_warning=0;

my $testopt=GetOptions(
           "add|a" => \$add,
           "move|m" => \$move,
           "kill|k" => \$kill,
           "help|h" => \$help,
           "skip|s" => \$skip_warning,
          );


# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);

my $ldap = &AD_bind_admin();
my $file_add=$DevelConf::path_result."/sophomorix.add";
my $file_move=$DevelConf::path_result."/sophomorix.move";
my $file_kill=$DevelConf::path_result."/sophomorix.kill";

my $testdata="/usr/share/sophomorix-developer/testdata";
my $file_add_test=$testdata."/sophomorix.add-1";
my $file_move_test=$testdata."/sophomorix.move-1";
my $file_kill_test=$testdata."/sophomorix.kill-1";

############################################################
# Check preliminaries
############################################################

# --add
if ($add==1){
    if (-e $file_add){
        print "\nTo run this test $file_add must not be there!\n\n";
        if ($skip_warning==0){
            exit;
        }
    }
    my @users=("koehleju","maier");
    foreach my $user (@users){
        my ($count,$dn_exist,$cn_exist)=&AD_object_search($ldap,"user",$user);
        if ($count > 0){
            print "\nTo run this test $user must not exist in AD!\n\n";
            if ($skip_warning==0){
                exit;
	    }
        }
    }
}


# --kill
if ($kill==1){
    if (-e $file_kill){
        print "\nTo run this test $file_kill must not be there!\n\n";
        if ($skip_warning==0){
            exit;
        }
    }
}

############################################################
# Run the tests
############################################################

############################################################
# Adding users --add
############################################################
if ($add==1){
    # copy sophomorix.add
    system("cp $file_add_test $file_add");
    system("sophomorix-add -i");
#    system("sophomorix-add");

    ##### Testing the user
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=maiersa42,CN=bsz-m7ab,CN=Students,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Sarina Maier",
                   givenName=>"Sarina",
                   name=>"maiersa42",
                   sAMAccountname=>"maiersa42",
                   sn=>"Maier",
                   sophomorixAdminClass => "bsz-m7ab",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Sarina",
                   sophomorixSurnameASCII  => "Maier",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-m7ab",
                   not_memberOf => "bsz-students,teachers,bsz-teachers,lin-teachers",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-m7ab,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-m7ab",
                   memberOf => "bsz-students",
                   not_memberOf => "teachers",
                  });
    ##### Testing the users ou-students group
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-students,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-students",
                   memberOf => "students",
                   not_memberOf => "teachers",
                  });


    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=muellegr42,CN=bsz-m7ab,CN=Students,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Gregor Müller",
                   givenName=>"Gregor",
                   name=>"muellegr42",
                   sAMAccountname=>"muellegr42",
                   sn=>"Müller",
                   sophomorixAdminClass => "bsz-m7ab",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Gregor",
                   sophomorixSurnameASCII  => "Mueller",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-m7ab",
                   not_memberOf => "bsz-students,teachers,bsz-teachers,lin-teachers",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=jonsonad42,CN=bsz-m8cd,CN=Students,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Aðalráður Jónsson",
                   givenName=>"Aðalráður",
                   name=>"jonsonad42",
                   sAMAccountname=>"jonsonad42",
                   sn=>"Jónsson",
                   sophomorixAdminClass => "bsz-m8cd",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Adalradur",
                   sophomorixSurnameASCII  => "Jonsson",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-m8cd",
                   not_memberOf => "bsz-students,teachers,bsz-teachers,lin-teachers",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=samardze42,CN=bsz-m8cd,CN=Students,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Željko Samardžić",
                   givenName=>"Željko",
                   name=>"samardze42",
                   sAMAccountname=>"samardze42",
                   sn=>"Samardžić",
                   sophomorixAdminClass => "bsz-m8cd",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Zeljko",
                   sophomorixSurnameASCII  => "Samardzic",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-m8cd",
                   not_memberOf => "bsz-students,teachers,bsz-teachers,lin-teachers",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-m8cd,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-m8cd",
                   memberOf => "bsz-students",
                   not_memberOf => "teachers",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=oe42,,CN=bsz-teachers,CN=Teachers,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Gökhan Ömür",
                   givenName=>"Gökhan",
                   name=>"oe42",
                   sAMAccountname=>"oe42",
                   sn=>"Ömür",
                   sophomorixAdminClass => "bsz-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster23!",
                   sophomorixFirstnameASCII => "Goekhan",
                   sophomorixSurnameASCII  => "Oemuer",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-teachers,",
                   not_memberOf => "teachers,lin-teachers,students",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=wu42,CN=bsz-teachers,CN=Teachers,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Désirée Würth",
                   givenName=>"Désirée",
                   name=>"wu42",
                   sAMAccountname=>"wu42",
                   sn=>"Würth",
                   sophomorixAdminClass => "bsz-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Desiree",
                   sophomorixSurnameASCII  => "Wuerth",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-teachers,",
                   not_memberOf => "teachers,lin-teachers,students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-teachers,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-teachers",
                   memberOf => "teachers",
                   not_memberOf => "students",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=blackmri42,CN=uni-12abc,CN=Students,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Richard Blackmore",
                   givenName=>"Richard",
                   name=>"blackmri42",
                   sAMAccountname=>"blackmri42",
                   sn=>"Blackmore",
                   sophomorixAdminClass => "uni-12abc",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Richard",
                   sophomorixSurnameASCII  => "Blackmore",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   memberOf => "uni-12abc,",
                   not_memberOf => "teachers,uni-teachers,lin-teachers,bsz-teachers,students",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=lordjo42,CN=uni-12abc,CN=Students,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Jon Lord",
                   givenName=>"Jon",
                   name=>"lordjo42",
                   sAMAccountname=>"lordjo42",
                   sn=>"Lord",
                   sophomorixAdminClass => "uni-12abc",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Jon",
                   sophomorixSurnameASCII  => "Lord",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   memberOf => "uni-12abc,",
                   not_memberOf => "teachers,uni-teachers,lin-teachers,bsz-teachers,students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=uni-12abc,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   sAMAccountname=>"uni-12abc",
                   memberOf => "uni-students",
                   not_memberOf => "students,uni-teachers",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=kep42,CN=uni-teachers,CN=Teachers,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Johannes Kepler",
                   givenName=>"Johannes",
                   name=>"kep42",
                   sAMAccountname=>"kep42",
                   sn=>"Kepler",
                   sophomorixAdminClass => "uni-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster23!",
                   sophomorixFirstnameASCII => "Johannes",
                   sophomorixSurnameASCII  => "Kepler",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   memberOf => "uni-teachers,",
                   not_memberOf => "teachers,lin-teachers,bsz-teachers,students",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=gal42,CN=uni-teachers,CN=Teachers,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Galileo Galilei",
                   givenName=>"Galileo",
                   name=>"gal42",
                   sAMAccountname=>"gal42",
                   sn=>"Galilei",
                   sophomorixAdminClass => "uni-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Galileo",
                   sophomorixSurnameASCII  => "Galilei",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   memberOf => "uni-teachers,",
                   not_memberOf => "teachers,lin-teachers,bsz-teachers,students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=uni-teachers,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   sAMAccountname=>"uni-teachers",
                   memberOf => "teachers",
                   not_memberOf => "students,uni-students",
                  });
}


############################################################
# Adding users --move
############################################################
if ($move==1){
    # copy sophomorix.move
    system("cp $file_move_test $file_move");
    system("sophomorix-move -i");
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=maiersa42,CN=bsz-attic,CN=Students,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Sarina Maier",
                   givenName=>"Sarina",
                   name=>"maiersa42",
                   sAMAccountname=>"maiersa42",
                   sn=>"Maier",
                   sophomorixAdminClass => "bsz-attic",
                   sophomorixExitAdminClass => "bsz-m7ab",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Sarina",
                   sophomorixSurnameASCII  => "Maier",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-attic",
                   not_memberOf => "teachers,bsz-teachers,lin-teachers",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-attic,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-attic",
                   memberOf => "bsz-students",
                   not_memberOf => "students,lin-students,uni-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-students,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-students",
                   memberOf => "students",
                   not_memberOf => "teachers",
                  });

    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=muellegr42,CN=lin-attic,CN=Students,OU=LINUXLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Gregor Müller",
                   givenName=>"Gregor",
                   name=>"muellegr42",
                   sAMAccountname=>"muellegr42",
                   sn=>"Müller",
                   sophomorixAdminClass => "lin-attic",
                   sophomorixExitAdminClass => "bsz-m7ab",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Gregor",
                   sophomorixSurnameASCII  => "Mueller",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "lin",
                   sophomorixSchoolname => "LINUXLEO",
                   memberOf => "lin-attic",
                   not_memberOf => "teachers,bsz-teachers,lin-teachers,bsz-students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=lin-attic,CN=Classes,OU=LINUXLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"lin-attic",
                   memberOf => "lin-students",
                   not_memberOf => "students,uni-students,bsz-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=lin-students,CN=Classes,OU=LINUXLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"lin-students",
                   memberOf => "students",
                   not_memberOf => "teachers",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=jonsonad42,CN=bsz-m9cd,CN=Students,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Aðalráður Jónsson",
                   givenName=>"Aðalráður",
                   name=>"jonsonad42",
                   sAMAccountname=>"jonsonad42",
                   sn=>"Jónsson",
                   sophomorixAdminClass => "bsz-m9cd",
                   sophomorixExitAdminClass => "bsz-m8cd",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Adalradur",
                   sophomorixSurnameASCII  => "Jonsson",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-m9cd",
                   not_memberOf => "teachers,bsz-teachers,lin-teachers,bsz-students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-m9cd,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-m9cd",
                   memberOf => "bsz-students",
                   not_memberOf => "students,uni-students,lin-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-students,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-students",
                   memberOf => "students",
                   not_memberOf => "teachers",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=samardze42,CN=bsz-m9cd,CN=Students,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Željko Samardžić",
                   givenName=>"Željko",
                   name=>"samardze42",
                   sAMAccountname=>"samardze42",
                   sn=>"Samardžić",
                   sophomorixAdminClass => "bsz-m9cd",
                   sophomorixExitAdminClass => "bsz-m8cd",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Zeljko",
                   sophomorixSurnameASCII  => "Samardzic",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-m9cd",
                   not_memberOf => "teachers,bsz-teachers,lin-teachers,bsz-students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-m9cd,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-m9cd",
                   memberOf => "bsz-students",
                   not_memberOf => "students,uni-students,lin-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-students,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-students",
                   memberOf => "students",
                   not_memberOf => "teachers",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=oe42,CN=bsz-alumni,CN=Students,OU=BSZLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Gökhan Ömür",
                   givenName=>"Gökhan",
                   name=>"oe42",
                   sAMAccountname=>"oe42",
                   sn=>"Ömür",
                   sophomorixAdminClass => "bsz-alumni",
                   sophomorixExitAdminClass => "bsz-teachers",
                   sophomorixFirstPassword => "LinuxMuster23!",
                   sophomorixFirstnameASCII => "Goekhan",
                   sophomorixSurnameASCII  => "Oemuer",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   memberOf => "bsz-alumni",
                   not_memberOf => "teachers,bsz-teachers,lin-teachers,bsz-students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-m9cd,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-m9cd",
                   memberOf => "bsz-students",
                   not_memberOf => "students,uni-students,lin-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=bsz-students,CN=Classes,OU=BSZLEO,DC=linuxmuster,DC=local",
                   sAMAccountname=>"bsz-students",
                   memberOf => "students",
                   not_memberOf => "teachers",
                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=wu42,CN=uni-teachers,CN=Teachers,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Désirée Würth",
                   givenName=>"Désirée",
                   name=>"wu42",
                   sAMAccountname=>"wu42",
                   sn=>"Würth",
                   sophomorixAdminClass => "uni-teachers",
                   sophomorixExitAdminClass => "bsz-teachers",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Desiree",
                   sophomorixSurnameASCII  => "Wuerth",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   memberOf => "uni-teachers",
                   not_memberOf => "teachers,bsz-teachers,lin-teachers,bsz-students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=uni-teachers,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   sAMAccountname=>"uni-teachers",
                   memberOf => "teachers",
                   not_memberOf => "students,uni-students,lin-students",
                  });
#    ##### Testing the users ou-students group
#    &AD_test_object_exist({ldap=>$ldap,
#                   dn=>"CN=bsz-students,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
#                   sAMAccountname=>"bsz-students",
#                   memberOf => "students",
#                   not_memberOf => "teachers",
#                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=lordjo42,CN=uni-teachers,CN=Teachers,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Jon Lord",
                   givenName=>"Jon",
                   name=>"lordjo42",
                   sAMAccountname=>"lordjo42",
                   sn=>"Lord",
                   sophomorixAdminClass => "uni-12-abc",
                   sophomorixExitAdminClass => "uni-teachers",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Jon",
                   sophomorixSurnameASCII  => "Lord",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   memberOf => "uni-teachers",
                   not_memberOf => "bsz-teachers,lin-teachers,bsz-students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=uni-teachers,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   sAMAccountname=>"uni-teachers",
                   memberOf => "teachers",
                   not_memberOf => "students,uni-students,lin-students",
                  });
#    ##### Testing the users ou-students group
#    &AD_test_object_exist({ldap=>$ldap,
#                   dn=>"CN=bsz-students,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
#                   sAMAccountname=>"bsz-students",
#                   memberOf => "students",
#                   not_memberOf => "teachers",
#                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=blackmri42,CN=lin-teachers,CN=Teachers,OU=LINUXLEO,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Richard Blackmore",
                   givenName=>"Richard",
                   name=>"blackmri42",
                   sAMAccountname=>"blackmri42",
                   sn=>"Blackmore",
                   sophomorixAdminClass => "lin-teachers",
                   sophomorixExitAdminClass => "uni-12-abc",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Richard",
                   sophomorixSurnameASCII  => "Blackmore",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "lin",
                   sophomorixSchoolname => "LINUXLEO",
                   memberOf => "lin-teachers",
                   not_memberOf => "bsz-teachers,lin-teachers,bsz-students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=uni-teachers,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   sAMAccountname=>"uni-teachers",
                   memberOf => "teachers",
                   not_memberOf => "students,uni-students,lin-students",
                  });
#    ##### Testing the users ou-students group
#    &AD_test_object_exist({ldap=>$ldap,
#                   dn=>"CN=bsz-students,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
#                   sAMAccountname=>"bsz-students",
#                   memberOf => "students",
#                   not_memberOf => "teachers",
#                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=kep42,CN=uni-alumni,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Johannes Kepler",
                   givenName=>"Johannes",
                   name=>"kep42",
                   sAMAccountname=>"kep42",
                   sn=>"Kepler",
                   sophomorixAdminClass => "uni-alumni",
                   sophomorixExitAdminClass => "uni-teachers",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Johannes",
                   sophomorixSurnameASCII  => "Kepler",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "lin",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   memberOf => "uni-alumni",
                   not_memberOf => "bsz-teachers,lin-teachers,bsz-students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=uni-alumni,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
                   sAMAccountname=>"uni-alumni",
                   memberOf => "uni-students",
                   not_memberOf => "students,lin-students",
                  });
#    ##### Testing the users ou-students group
#    &AD_test_object_exist({ldap=>$ldap,
#                   dn=>"CN=bsz-students,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
#                   sAMAccountname=>"bsz-students",
#                   memberOf => "students",
#                   not_memberOf => "teachers",
#                  });
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=gal42,CN=ghs-alumni,CN=Classes,OU=GHS-SCHOOL,DC=linuxmuster,DC=local",
                   #####
                   displayName=>"Galileo Galilei",
                   givenName=>"Galileo",
                   name=>"gal42",
                   sAMAccountname=>"gal42",
                   sn=>"Galilei",
                   sophomorixAdminClass => "ghs-alumni",
                   sophomorixExitAdminClass => "uni-teachers",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Galileo",
                   sophomorixSurnameASCII  => "Galilei",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "lin",
                   sophomorixSchoolname => "GHS-SCHOOL",
                   memberOf => "ghs-alumni",
                   not_memberOf => "uni-teachers,lin-teachers,bsz-students",
                  });
    ##### Testing the users class
    &AD_test_object_exist({ldap=>$ldap,
                   dn=>"CN=ghs-alumni,CN=Classes,OU=GHS-SCHOOL,DC=linuxmuster,DC=local",
                   sAMAccountname=>"ghs-alumni",
                   memberOf => "ghs-students",
                   not_memberOf => "students,lin-students",
                  });
#    ##### Testing the users ou-students group
#    &AD_test_object_exist({ldap=>$ldap,
#                   dn=>"CN=bsz-students,CN=Classes,OU=UNIVERSITÄT,DC=linuxmuster,DC=local",
#                   sAMAccountname=>"bsz-students",
#                   memberOf => "students",
#                   not_memberOf => "teachers",
#                  });
}




############################################################
# Deleting users --kill
############################################################
if ($kill==1){
    # copy sophomorix.kill
    system("cp $file_kill_test $file_kill");
    system("sophomorix-kill -i");
    system("sophomorix-kill");

}



&AD_unbind_admin($ldap);



