#!/usr/bin/perl -w
# This script (sophomorix-groupadd) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or jeffbeck@linuxmuster.net


# Bibliotheken
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use Net::LDAP;
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 time_stamp_AD
                                 time_stamp_file
                                 log_script_start
                                 log_script_end
                                 log_script_exit
                                 check_options
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_group_create
                                 AD_group_addmembers
                                 AD_group_removemembers
                                 get_forbidden_logins
                                    );

my @arguments = @ARGV;


# ===========================================================================
# Variablen
# ==========================================================================

my $help=0;
my $info=0;

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================

$Conf::log_level=1;

my $group="";
my $addmembers="";
my $removemembers="";

my $skiplock=0;

my $type=-1; # 3: domain group

# Parsen der Optionen
my $testopt=GetOptions(
           "help|h" => \$help,
           "info|i" => \$info,
           "group=s" => \$group,
           "addmembers=s" => \$addmembers,
           "removemembers=s" => \$removemembers,
           "skiplock" => \$skiplock,
          );

# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);



# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-groupadd adds a group to samba 4 AD

Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose
  -i  / --info (unused)
  --addmembers member
  --removemembers member
  --group name

Please see the sophomorix-groupadd(8) man pages for full documentation
');
   print "\n";
   exit;
}


# --info
if ($info==1){
    print "No Option --info\n";
    exit;
}



# exit if options are missing
if ($group eq ""){ 
     print "\nThe option:\n";
     print "   --group name \n";
     print "is mandatory.\n\n";
     exit;
}

&log_script_start(@arguments);


my $ldap = &AD_bind_admin();

# make sure group exists
&AD_group_create({ldap=>$ldap, 
                 group=>$group,
                });


# --removemembers member
if ($removemembers ne ""){
    &AD_group_removemembers({ldap => $ldap, 
                             group => $group,
                             removemembers => $removemembers,
                           });   
}


# --addmembers member
if ($addmembers ne ""){
    &AD_group_addmembers({ldap => $ldap, 
                          group => $group,
                          addmembers => $addmembers,
                        });   
}

&AD_unbind_admin($ldap);

&log_script_end(@arguments);
