#!/bin/sh

if [ -z "$1" ]; then
    echo "Give option for the appendix of the backup files"
else
    /etc/init.d/samba stop

    find /var/lib/samba/private -name '*.ldb' -exec echo cp {}-$1 {} \;

    /etc/init.d/samba start
fi



