#!/bin/sh
#DATE=`date +"%Y-%m-%d_%H_%M_%S"`
#echo $DATE

if [ -z "$1" ]; then
    echo "Give option for the appendix of the backup files"
else
    find /var/lib/samba/private -name '*.ldb' -exec tdbbackup -s "-$1" {} \;
fi
